function configureSceneCameraWithDefaultSettings()
    SceneCamera:setPosition(glm.vec3(0.0, 0.0, 0.0))
    SceneCamera:setMoveSpeed(1.0)
    SceneCamera:setRotationSpeed(1.0)
    SceneCamera:setFieldOfView(45.0)
    SceneCamera:setNearClip(0.1)
    SceneCamera:setFarClip(100.0)
    SceneCamera:setYaw(0.0)
    SceneCamera:setPitch(0.0)
    SceneCamera:setRoll(0.0)
    SceneCamera:setOrientation(glm.quat(1.0, 0.0, 0.0, 0.0))
    SceneCamera:setWorldUpDirection(WORLD_UP_DIRECTION)
    SceneCamera:setUpDirection(WORLD_UP_DIRECTION)
    SceneCamera:setRightDirection(WORLD_RIGHT_DIRECTION)
    SceneCamera:setForwardDirection(WORLD_FORWARD_DIRECTION)
end
