function(compile_shader SHADER)
    set(SHADER_SRC_PATH ${SHADER_SRC_DIR}/${SHADER})
    set(SHADER_DST_PATH ${SHADER_DST_DIR}/${SHADER}.spv)
    find_program(GLSLC glslc)
    get_filename_component(DST_DIR ${SHADER_DST_PATH} DIRECTORY)
    file(MAKE_DIRECTORY ${DST_DIR})
    execute_process(COMMAND ${GLSLC} -o ${SHADER_DST_PATH} ${SHADER_SRC_PATH})
endfunction()

function(compile_shaders WILDCARD)
    file(GLOB files "${SHADER_SRC_DIR}/${WILDCARD}")
    foreach (file ${files})
        get_filename_component(FILENAME ${file} NAME)
        compile_shader(${FILENAME})
    endforeach ()
endfunction()

compile_shaders(*.vert)
compile_shaders(*.frag)